ERM_TRAIN:
  ENABLE: True
  DATASET: Ssv2_webm
  BATCH_SIZE: 14
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  FP16: True
  FINETUNE: False
  NUM_ITERS: 1
DATA:
  PATH_TO_ANNOTATION: '/data/jongseo/project/cil/temporal-selfsupervision/labels'
  PATH_TO_JPEG: '/local_datasets/something-something-v2/videos'
  TRAIN_SPLIT_DIR: ''
  VAL_SPLIT_DIR: ''
  MEAN: [ 0.5, 0.5, 0.5 ]
  STD: [ 0.5, 0.5, 0.5 ]
  USE_RAND_AUGMENT: True
  TRAIN_JITTER_SCALES: [ 256, 320 ]
  TRAIN_CROP_SIZE: 224
  RANDOM_FLIP: False
  INV_UNIFORM_SAMPLE: True
  REVERSE_INPUT_CHANNEL: True
  NUM_FRAMES: 8
SOLVER:
  BASE_LR: 1e-4
  LR_POLICY: steps_with_relative_lrs
  LRS: [ 1, 0.1, 0.01 ]
  STEPS: [ 0, 20, 30 ]
  MAX_EPOCH: 35
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-2
  WARMUP_EPOCHS: 0.0
  SMOOTHING: 0.2
  OPTIMIZING_METHOD: adamw
MODEL:
  NUM_CLASSES: 174
  MODEL_NAME: timesformer_vit_base_patch16_224
  LOSS_FUNC: cross_entropy
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: True
NUM_GPUS: 2
LOG_PERIOD: 10
RNG_SEED: 0
OUTPUT_DIR: ./experiments/timesformer_8frame
ERM_TEST:
  ENABLE: True
  DATASET: Ssv2_webm
  BATCH_SIZE: 128